export default [
    {
        cardType: "fundraising",
        cardTitle: "Take back the courts!",
        cardUser: "Cooper Michael",
        created: "1575587402133",
        cardID: "1",
        cardSummary: "Donate to help our campaign to impeach partisan judges and take back the courts for the people!",
        cardContent: "All money donated will go towards our non-profit that targets senetors in battleground states. We inform them of the impropriety of recently elected partisan judges and convince them to act! Our country will be a better place with judges that choose to follow black letter law rather than red or blue ideology.",
        imgUrl: "./imgs/Courts.jpg",
        imgTitle: "Courts",
        fundingGoal: "10000",
        fundingRaised: "5000",
        eventLocation: null,
        eventDate: null,
        eventTime: null,
    },
    {
        cardType: "event",
        cardTitle: "Protest for climate change!",
        cardUser: "Sayaka Tsutsumi",
        created: "1575608906977",
        cardID: "2",
        cardSummary: "Come out to make your voice heard. Let's save the planet together",
        cardContent: "A recent report says that climate change scientists have actually UNDERESTIMATED the effects of climate change and in fact it will get much worse than previously thought. We must call attention to the planets mortality and act now before it is too late.",
        imgUrl: "./imgs/protest.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "discussion",
        cardTitle: "What is the best solution for income inequality?",
        cardUser: "David Michael",
        created: "1575681753533",
        cardID: "3",
        cardSummary: "We all know that wealth inequality is at an all time high, what can we do to fix it?",
        cardContent: "I've seen reports of CEOs making over 300 times thier lowest paid employees. What if the government imposed a maximum ratio for wage differences. For example a regulation that says no one employee can make more than 50 times any other employee. This will solve more problems than simple taxation. It will motivate employees to do better work since they share in the profits and help the economy as a whole by distributing the money of the wealthiest companies to more people enabling more of it to flow back into the economy. What do you think?",
        imgUrl: "./imgs/income-inequality.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "fundraising",
        cardTitle: "Take back the courts!",
        cardUser: "Cooper Michael",
        created: "1575587402133",
        cardID: "1",
        cardSummary: "Donate to help our campaign to impeach partisan judges and take back the courts for the people!",
        cardContent: "All money donated will go towards our non-profit that targets senetors in battleground states. We inform them of the impropriety of recently elected partisan judges and convince them to act! Our country will be a better place with judges that choose to follow black letter law rather than red or blue ideology.",
        imgUrl: "./imgs/Courts.jpg",
        imgTitle: "Courts",
        fundingGoal: "10000",
        fundingRaised: "5000",
        eventLocation: null,
        eventDate: null,
        eventTime: null,
    },
    {
        cardType: "event",
        cardTitle: "Protest for climate change!",
        cardUser: "Sayaka Tsutsumi",
        created: "1575608906977",
        cardID: "2",
        cardSummary: "Come out to make your voice heard. Let's save the planet together",
        cardContent: "A recent report says that climate change scientists have actually UNDERESTIMATED the effects of climate change and in fact it will get much worse than previously thought. We must call attention to the planets mortality and act now before it is too late.",
        imgUrl: "./imgs/protest.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "discussion",
        cardTitle: "What is the best solution for income inequality?",
        cardUser: "David Michael",
        created: "1575681753533",
        cardID: "3",
        cardSummary: "We all know that wealth inequality is at an all time high, what can we do to fix it?",
        cardContent: "I've seen reports of CEOs making over 300 times thier lowest paid employees. What if the government imposed a maximum ratio for wage differences. For example a regulation that says no one employee can make more than 50 times any other employee. This will solve more problems than simple taxation. It will motivate employees to do better work since they share in the profits and help the economy as a whole by distributing the money of the wealthiest companies to more people enabling more of it to flow back into the economy. What do you think?",
        imgUrl: "./imgs/income-inequality.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "fundraising",
        cardTitle: "Take back the courts!",
        cardUser: "Cooper Michael",
        created: "1575587402133",
        cardID: "1",
        cardSummary: "Donate to help our campaign to impeach partisan judges and take back the courts for the people!",
        cardContent: "All money donated will go towards our non-profit that targets senetors in battleground states. We inform them of the impropriety of recently elected partisan judges and convince them to act! Our country will be a better place with judges that choose to follow black letter law rather than red or blue ideology.",
        imgUrl: "./imgs/Courts.jpg",
        imgTitle: "Courts",
        fundingGoal: "10000",
        fundingRaised: "5000",
        eventLocation: null,
        eventDate: null,
        eventTime: null,
    },
    {
        cardType: "event",
        cardTitle: "Protest for climate change!",
        cardUser: "Sayaka Tsutsumi",
        created: "1575608906977",
        cardID: "2",
        cardSummary: "Come out to make your voice heard. Let's save the planet together",
        cardContent: "A recent report says that climate change scientists have actually UNDERESTIMATED the effects of climate change and in fact it will get much worse than previously thought. We must call attention to the planets mortality and act now before it is too late.",
        imgUrl: "./imgs/protest.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "discussion",
        cardTitle: "What is the best solution for income inequality?",
        cardUser: "David Michael",
        created: "1575681753533",
        cardID: "3",
        cardSummary: "We all know that wealth inequality is at an all time high, what can we do to fix it?",
        cardContent: "I've seen reports of CEOs making over 300 times thier lowest paid employees. What if the government imposed a maximum ratio for wage differences. For example a regulation that says no one employee can make more than 50 times any other employee. This will solve more problems than simple taxation. It will motivate employees to do better work since they share in the profits and help the economy as a whole by distributing the money of the wealthiest companies to more people enabling more of it to flow back into the economy. What do you think?",
        imgUrl: "./imgs/income-inequality.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "fundraising",
        cardTitle: "Take back the courts!",
        cardUser: "Cooper Michael",
        created: "1575587402133",
        cardID: "1",
        cardSummary: "Donate to help our campaign to impeach partisan judges and take back the courts for the people!",
        cardContent: "All money donated will go towards our non-profit that targets senetors in battleground states. We inform them of the impropriety of recently elected partisan judges and convince them to act! Our country will be a better place with judges that choose to follow black letter law rather than red or blue ideology.",
        imgUrl: "./imgs/Courts.jpg",
        imgTitle: "Courts",
        fundingGoal: "10000",
        fundingRaised: "5000",
        eventLocation: null,
        eventDate: null,
        eventTime: null,
    },
    {
        cardType: "event",
        cardTitle: "Protest for climate change!",
        cardUser: "Sayaka Tsutsumi",
        created: "1575608906977",
        cardID: "2",
        cardSummary: "Come out to make your voice heard. Let's save the planet together",
        cardContent: "A recent report says that climate change scientists have actually UNDERESTIMATED the effects of climate change and in fact it will get much worse than previously thought. We must call attention to the planets mortality and act now before it is too late.",
        imgUrl: "./imgs/protest.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    },
    {
        cardType: "discussion",
        cardTitle: "What is the best solution for income inequality?",
        cardUser: "David Michael",
        created: "1575681753533",
        cardID: "3",
        cardSummary: "We all know that wealth inequality is at an all time high, what can we do to fix it?",
        cardContent: "I've seen reports of CEOs making over 300 times thier lowest paid employees. What if the government imposed a maximum ratio for wage differences. For example a regulation that says no one employee can make more than 50 times any other employee. This will solve more problems than simple taxation. It will motivate employees to do better work since they share in the profits and help the economy as a whole by distributing the money of the wealthiest companies to more people enabling more of it to flow back into the economy. What do you think?",
        imgUrl: "./imgs/income-inequality.jpg",
        imgTitle: "Climate Change",
        fundingGoal: null,
        fundingRaised: null,
        eventLocation: 'Berkeley, CA',
        eventDate: 'August 19, 2020 14:00:00',
    }
]